// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gcsystemmsgs.proto

/*
	Package gcsystemmsgs is a generated protocol buffer package.

	It is generated from these files:
		gcsystemmsgs.proto

	It has these top-level messages:
		CMsgGCHVacVerificationChange
		CMsgGCHAccountPhoneNumberChange
*/
package gcsystemmsgs

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type EGCSystemMsg int32

const (
	EGCSystemMsg_k_EGCMsgInvalid                           EGCSystemMsg = 0
	EGCSystemMsg_k_EGCMsgMulti                             EGCSystemMsg = 1
	EGCSystemMsg_k_EGCMsgGenericReply                      EGCSystemMsg = 10
	EGCSystemMsg_k_EGCMsgSystemBase                        EGCSystemMsg = 50
	EGCSystemMsg_k_EGCMsgAchievementAwarded                EGCSystemMsg = 51
	EGCSystemMsg_k_EGCMsgConCommand                        EGCSystemMsg = 52
	EGCSystemMsg_k_EGCMsgStartPlaying                      EGCSystemMsg = 53
	EGCSystemMsg_k_EGCMsgStopPlaying                       EGCSystemMsg = 54
	EGCSystemMsg_k_EGCMsgStartGameserver                   EGCSystemMsg = 55
	EGCSystemMsg_k_EGCMsgStopGameserver                    EGCSystemMsg = 56
	EGCSystemMsg_k_EGCMsgWGRequest                         EGCSystemMsg = 57
	EGCSystemMsg_k_EGCMsgWGResponse                        EGCSystemMsg = 58
	EGCSystemMsg_k_EGCMsgGetUserGameStatsSchema            EGCSystemMsg = 59
	EGCSystemMsg_k_EGCMsgGetUserGameStatsSchemaResponse    EGCSystemMsg = 60
	EGCSystemMsg_k_EGCMsgGetUserStatsDEPRECATED            EGCSystemMsg = 61
	EGCSystemMsg_k_EGCMsgGetUserStatsResponse              EGCSystemMsg = 62
	EGCSystemMsg_k_EGCMsgAppInfoUpdated                    EGCSystemMsg = 63
	EGCSystemMsg_k_EGCMsgValidateSession                   EGCSystemMsg = 64
	EGCSystemMsg_k_EGCMsgValidateSessionResponse           EGCSystemMsg = 65
	EGCSystemMsg_k_EGCMsgLookupAccountFromInput            EGCSystemMsg = 66
	EGCSystemMsg_k_EGCMsgSendHTTPRequest                   EGCSystemMsg = 67
	EGCSystemMsg_k_EGCMsgSendHTTPRequestResponse           EGCSystemMsg = 68
	EGCSystemMsg_k_EGCMsgPreTestSetup                      EGCSystemMsg = 69
	EGCSystemMsg_k_EGCMsgRecordSupportAction               EGCSystemMsg = 70
	EGCSystemMsg_k_EGCMsgGetAccountDetails_DEPRECATED      EGCSystemMsg = 71
	EGCSystemMsg_k_EGCMsgReceiveInterAppMessage            EGCSystemMsg = 73
	EGCSystemMsg_k_EGCMsgFindAccounts                      EGCSystemMsg = 74
	EGCSystemMsg_k_EGCMsgPostAlert                         EGCSystemMsg = 75
	EGCSystemMsg_k_EGCMsgGetLicenses                       EGCSystemMsg = 76
	EGCSystemMsg_k_EGCMsgGetUserStats                      EGCSystemMsg = 77
	EGCSystemMsg_k_EGCMsgGetCommands                       EGCSystemMsg = 78
	EGCSystemMsg_k_EGCMsgGetCommandsResponse               EGCSystemMsg = 79
	EGCSystemMsg_k_EGCMsgAddFreeLicense                    EGCSystemMsg = 80
	EGCSystemMsg_k_EGCMsgAddFreeLicenseResponse            EGCSystemMsg = 81
	EGCSystemMsg_k_EGCMsgGetIPLocation                     EGCSystemMsg = 82
	EGCSystemMsg_k_EGCMsgGetIPLocationResponse             EGCSystemMsg = 83
	EGCSystemMsg_k_EGCMsgSystemStatsSchema                 EGCSystemMsg = 84
	EGCSystemMsg_k_EGCMsgGetSystemStats                    EGCSystemMsg = 85
	EGCSystemMsg_k_EGCMsgGetSystemStatsResponse            EGCSystemMsg = 86
	EGCSystemMsg_k_EGCMsgSendEmail                         EGCSystemMsg = 87
	EGCSystemMsg_k_EGCMsgSendEmailResponse                 EGCSystemMsg = 88
	EGCSystemMsg_k_EGCMsgGetEmailTemplate                  EGCSystemMsg = 89
	EGCSystemMsg_k_EGCMsgGetEmailTemplateResponse          EGCSystemMsg = 90
	EGCSystemMsg_k_EGCMsgGrantGuestPass                    EGCSystemMsg = 91
	EGCSystemMsg_k_EGCMsgGrantGuestPassResponse            EGCSystemMsg = 92
	EGCSystemMsg_k_EGCMsgGetAccountDetails                 EGCSystemMsg = 93
	EGCSystemMsg_k_EGCMsgGetAccountDetailsResponse         EGCSystemMsg = 94
	EGCSystemMsg_k_EGCMsgGetPersonaNames                   EGCSystemMsg = 95
	EGCSystemMsg_k_EGCMsgGetPersonaNamesResponse           EGCSystemMsg = 96
	EGCSystemMsg_k_EGCMsgMultiplexMsg                      EGCSystemMsg = 97
	EGCSystemMsg_k_EGCMsgMultiplexMsgResponse              EGCSystemMsg = 98
	EGCSystemMsg_k_EGCMsgWebAPIRegisterInterfaces          EGCSystemMsg = 101
	EGCSystemMsg_k_EGCMsgWebAPIJobRequest                  EGCSystemMsg = 102
	EGCSystemMsg_k_EGCMsgWebAPIJobRequestHttpResponse      EGCSystemMsg = 104
	EGCSystemMsg_k_EGCMsgWebAPIJobRequestForwardResponse   EGCSystemMsg = 105
	EGCSystemMsg_k_EGCMsgMemCachedGet                      EGCSystemMsg = 200
	EGCSystemMsg_k_EGCMsgMemCachedGetResponse              EGCSystemMsg = 201
	EGCSystemMsg_k_EGCMsgMemCachedSet                      EGCSystemMsg = 202
	EGCSystemMsg_k_EGCMsgMemCachedDelete                   EGCSystemMsg = 203
	EGCSystemMsg_k_EGCMsgMemCachedStats                    EGCSystemMsg = 204
	EGCSystemMsg_k_EGCMsgMemCachedStatsResponse            EGCSystemMsg = 205
	EGCSystemMsg_k_EGCMsgMasterSetDirectory                EGCSystemMsg = 220
	EGCSystemMsg_k_EGCMsgMasterSetDirectoryResponse        EGCSystemMsg = 221
	EGCSystemMsg_k_EGCMsgMasterSetWebAPIRouting            EGCSystemMsg = 222
	EGCSystemMsg_k_EGCMsgMasterSetWebAPIRoutingResponse    EGCSystemMsg = 223
	EGCSystemMsg_k_EGCMsgMasterSetClientMsgRouting         EGCSystemMsg = 224
	EGCSystemMsg_k_EGCMsgMasterSetClientMsgRoutingResponse EGCSystemMsg = 225
	EGCSystemMsg_k_EGCMsgSetOptions                        EGCSystemMsg = 226
	EGCSystemMsg_k_EGCMsgSetOptionsResponse                EGCSystemMsg = 227
	EGCSystemMsg_k_EGCMsgSystemBase2                       EGCSystemMsg = 500
	EGCSystemMsg_k_EGCMsgGetPurchaseTrustStatus            EGCSystemMsg = 501
	EGCSystemMsg_k_EGCMsgGetPurchaseTrustStatusResponse    EGCSystemMsg = 502
	EGCSystemMsg_k_EGCMsgUpdateSession                     EGCSystemMsg = 503
	EGCSystemMsg_k_EGCMsgGCAccountVacStatusChange          EGCSystemMsg = 504
	EGCSystemMsg_k_EGCMsgCheckFriendship                   EGCSystemMsg = 505
	EGCSystemMsg_k_EGCMsgCheckFriendshipResponse           EGCSystemMsg = 506
	EGCSystemMsg_k_EGCMsgVacVerificationChange             EGCSystemMsg = 518
	EGCSystemMsg_k_EGCMsgAccountPhoneNumberChange          EGCSystemMsg = 519
)

var EGCSystemMsg_name = map[int32]string{
	0:   "k_EGCMsgInvalid",
	1:   "k_EGCMsgMulti",
	10:  "k_EGCMsgGenericReply",
	50:  "k_EGCMsgSystemBase",
	51:  "k_EGCMsgAchievementAwarded",
	52:  "k_EGCMsgConCommand",
	53:  "k_EGCMsgStartPlaying",
	54:  "k_EGCMsgStopPlaying",
	55:  "k_EGCMsgStartGameserver",
	56:  "k_EGCMsgStopGameserver",
	57:  "k_EGCMsgWGRequest",
	58:  "k_EGCMsgWGResponse",
	59:  "k_EGCMsgGetUserGameStatsSchema",
	60:  "k_EGCMsgGetUserGameStatsSchemaResponse",
	61:  "k_EGCMsgGetUserStatsDEPRECATED",
	62:  "k_EGCMsgGetUserStatsResponse",
	63:  "k_EGCMsgAppInfoUpdated",
	64:  "k_EGCMsgValidateSession",
	65:  "k_EGCMsgValidateSessionResponse",
	66:  "k_EGCMsgLookupAccountFromInput",
	67:  "k_EGCMsgSendHTTPRequest",
	68:  "k_EGCMsgSendHTTPRequestResponse",
	69:  "k_EGCMsgPreTestSetup",
	70:  "k_EGCMsgRecordSupportAction",
	71:  "k_EGCMsgGetAccountDetails_DEPRECATED",
	73:  "k_EGCMsgReceiveInterAppMessage",
	74:  "k_EGCMsgFindAccounts",
	75:  "k_EGCMsgPostAlert",
	76:  "k_EGCMsgGetLicenses",
	77:  "k_EGCMsgGetUserStats",
	78:  "k_EGCMsgGetCommands",
	79:  "k_EGCMsgGetCommandsResponse",
	80:  "k_EGCMsgAddFreeLicense",
	81:  "k_EGCMsgAddFreeLicenseResponse",
	82:  "k_EGCMsgGetIPLocation",
	83:  "k_EGCMsgGetIPLocationResponse",
	84:  "k_EGCMsgSystemStatsSchema",
	85:  "k_EGCMsgGetSystemStats",
	86:  "k_EGCMsgGetSystemStatsResponse",
	87:  "k_EGCMsgSendEmail",
	88:  "k_EGCMsgSendEmailResponse",
	89:  "k_EGCMsgGetEmailTemplate",
	90:  "k_EGCMsgGetEmailTemplateResponse",
	91:  "k_EGCMsgGrantGuestPass",
	92:  "k_EGCMsgGrantGuestPassResponse",
	93:  "k_EGCMsgGetAccountDetails",
	94:  "k_EGCMsgGetAccountDetailsResponse",
	95:  "k_EGCMsgGetPersonaNames",
	96:  "k_EGCMsgGetPersonaNamesResponse",
	97:  "k_EGCMsgMultiplexMsg",
	98:  "k_EGCMsgMultiplexMsgResponse",
	101: "k_EGCMsgWebAPIRegisterInterfaces",
	102: "k_EGCMsgWebAPIJobRequest",
	104: "k_EGCMsgWebAPIJobRequestHttpResponse",
	105: "k_EGCMsgWebAPIJobRequestForwardResponse",
	200: "k_EGCMsgMemCachedGet",
	201: "k_EGCMsgMemCachedGetResponse",
	202: "k_EGCMsgMemCachedSet",
	203: "k_EGCMsgMemCachedDelete",
	204: "k_EGCMsgMemCachedStats",
	205: "k_EGCMsgMemCachedStatsResponse",
	220: "k_EGCMsgMasterSetDirectory",
	221: "k_EGCMsgMasterSetDirectoryResponse",
	222: "k_EGCMsgMasterSetWebAPIRouting",
	223: "k_EGCMsgMasterSetWebAPIRoutingResponse",
	224: "k_EGCMsgMasterSetClientMsgRouting",
	225: "k_EGCMsgMasterSetClientMsgRoutingResponse",
	226: "k_EGCMsgSetOptions",
	227: "k_EGCMsgSetOptionsResponse",
	500: "k_EGCMsgSystemBase2",
	501: "k_EGCMsgGetPurchaseTrustStatus",
	502: "k_EGCMsgGetPurchaseTrustStatusResponse",
	503: "k_EGCMsgUpdateSession",
	504: "k_EGCMsgGCAccountVacStatusChange",
	505: "k_EGCMsgCheckFriendship",
	506: "k_EGCMsgCheckFriendshipResponse",
	518: "k_EGCMsgVacVerificationChange",
	519: "k_EGCMsgAccountPhoneNumberChange",
}
var EGCSystemMsg_value = map[string]int32{
	"k_EGCMsgInvalid":                           0,
	"k_EGCMsgMulti":                             1,
	"k_EGCMsgGenericReply":                      10,
	"k_EGCMsgSystemBase":                        50,
	"k_EGCMsgAchievementAwarded":                51,
	"k_EGCMsgConCommand":                        52,
	"k_EGCMsgStartPlaying":                      53,
	"k_EGCMsgStopPlaying":                       54,
	"k_EGCMsgStartGameserver":                   55,
	"k_EGCMsgStopGameserver":                    56,
	"k_EGCMsgWGRequest":                         57,
	"k_EGCMsgWGResponse":                        58,
	"k_EGCMsgGetUserGameStatsSchema":            59,
	"k_EGCMsgGetUserGameStatsSchemaResponse":    60,
	"k_EGCMsgGetUserStatsDEPRECATED":            61,
	"k_EGCMsgGetUserStatsResponse":              62,
	"k_EGCMsgAppInfoUpdated":                    63,
	"k_EGCMsgValidateSession":                   64,
	"k_EGCMsgValidateSessionResponse":           65,
	"k_EGCMsgLookupAccountFromInput":            66,
	"k_EGCMsgSendHTTPRequest":                   67,
	"k_EGCMsgSendHTTPRequestResponse":           68,
	"k_EGCMsgPreTestSetup":                      69,
	"k_EGCMsgRecordSupportAction":               70,
	"k_EGCMsgGetAccountDetails_DEPRECATED":      71,
	"k_EGCMsgReceiveInterAppMessage":            73,
	"k_EGCMsgFindAccounts":                      74,
	"k_EGCMsgPostAlert":                         75,
	"k_EGCMsgGetLicenses":                       76,
	"k_EGCMsgGetUserStats":                      77,
	"k_EGCMsgGetCommands":                       78,
	"k_EGCMsgGetCommandsResponse":               79,
	"k_EGCMsgAddFreeLicense":                    80,
	"k_EGCMsgAddFreeLicenseResponse":            81,
	"k_EGCMsgGetIPLocation":                     82,
	"k_EGCMsgGetIPLocationResponse":             83,
	"k_EGCMsgSystemStatsSchema":                 84,
	"k_EGCMsgGetSystemStats":                    85,
	"k_EGCMsgGetSystemStatsResponse":            86,
	"k_EGCMsgSendEmail":                         87,
	"k_EGCMsgSendEmailResponse":                 88,
	"k_EGCMsgGetEmailTemplate":                  89,
	"k_EGCMsgGetEmailTemplateResponse":          90,
	"k_EGCMsgGrantGuestPass":                    91,
	"k_EGCMsgGrantGuestPassResponse":            92,
	"k_EGCMsgGetAccountDetails":                 93,
	"k_EGCMsgGetAccountDetailsResponse":         94,
	"k_EGCMsgGetPersonaNames":                   95,
	"k_EGCMsgGetPersonaNamesResponse":           96,
	"k_EGCMsgMultiplexMsg":                      97,
	"k_EGCMsgMultiplexMsgResponse":              98,
	"k_EGCMsgWebAPIRegisterInterfaces":          101,
	"k_EGCMsgWebAPIJobRequest":                  102,
	"k_EGCMsgWebAPIJobRequestHttpResponse":      104,
	"k_EGCMsgWebAPIJobRequestForwardResponse":   105,
	"k_EGCMsgMemCachedGet":                      200,
	"k_EGCMsgMemCachedGetResponse":              201,
	"k_EGCMsgMemCachedSet":                      202,
	"k_EGCMsgMemCachedDelete":                   203,
	"k_EGCMsgMemCachedStats":                    204,
	"k_EGCMsgMemCachedStatsResponse":            205,
	"k_EGCMsgMasterSetDirectory":                220,
	"k_EGCMsgMasterSetDirectoryResponse":        221,
	"k_EGCMsgMasterSetWebAPIRouting":            222,
	"k_EGCMsgMasterSetWebAPIRoutingResponse":    223,
	"k_EGCMsgMasterSetClientMsgRouting":         224,
	"k_EGCMsgMasterSetClientMsgRoutingResponse": 225,
	"k_EGCMsgSetOptions":                        226,
	"k_EGCMsgSetOptionsResponse":                227,
	"k_EGCMsgSystemBase2":                       500,
	"k_EGCMsgGetPurchaseTrustStatus":            501,
	"k_EGCMsgGetPurchaseTrustStatusResponse":    502,
	"k_EGCMsgUpdateSession":                     503,
	"k_EGCMsgGCAccountVacStatusChange":          504,
	"k_EGCMsgCheckFriendship":                   505,
	"k_EGCMsgCheckFriendshipResponse":           506,
	"k_EGCMsgVacVerificationChange":             518,
	"k_EGCMsgAccountPhoneNumberChange":          519,
}

func (x EGCSystemMsg) Enum() *EGCSystemMsg {
	p := new(EGCSystemMsg)
	*p = x
	return p
}
func (x EGCSystemMsg) String() string {
	return proto.EnumName(EGCSystemMsg_name, int32(x))
}
func (x *EGCSystemMsg) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGCSystemMsg_value, data, "EGCSystemMsg")
	if err != nil {
		return err
	}
	*x = EGCSystemMsg(value)
	return nil
}
func (EGCSystemMsg) EnumDescriptor() ([]byte, []int) { return fileDescriptorGcsystemmsgs, []int{0} }

type ESOMsg int32

const (
	ESOMsg_k_ESOMsg_Create                   ESOMsg = 21
	ESOMsg_k_ESOMsg_Update                   ESOMsg = 22
	ESOMsg_k_ESOMsg_Destroy                  ESOMsg = 23
	ESOMsg_k_ESOMsg_CacheSubscribed          ESOMsg = 24
	ESOMsg_k_ESOMsg_CacheUnsubscribed        ESOMsg = 25
	ESOMsg_k_ESOMsg_UpdateMultiple           ESOMsg = 26
	ESOMsg_k_ESOMsg_CacheSubscriptionCheck   ESOMsg = 27
	ESOMsg_k_ESOMsg_CacheSubscriptionRefresh ESOMsg = 28
)

var ESOMsg_name = map[int32]string{
	21: "k_ESOMsg_Create",
	22: "k_ESOMsg_Update",
	23: "k_ESOMsg_Destroy",
	24: "k_ESOMsg_CacheSubscribed",
	25: "k_ESOMsg_CacheUnsubscribed",
	26: "k_ESOMsg_UpdateMultiple",
	27: "k_ESOMsg_CacheSubscriptionCheck",
	28: "k_ESOMsg_CacheSubscriptionRefresh",
}
var ESOMsg_value = map[string]int32{
	"k_ESOMsg_Create":                   21,
	"k_ESOMsg_Update":                   22,
	"k_ESOMsg_Destroy":                  23,
	"k_ESOMsg_CacheSubscribed":          24,
	"k_ESOMsg_CacheUnsubscribed":        25,
	"k_ESOMsg_UpdateMultiple":           26,
	"k_ESOMsg_CacheSubscriptionCheck":   27,
	"k_ESOMsg_CacheSubscriptionRefresh": 28,
}

func (x ESOMsg) Enum() *ESOMsg {
	p := new(ESOMsg)
	*p = x
	return p
}
func (x ESOMsg) String() string {
	return proto.EnumName(ESOMsg_name, int32(x))
}
func (x *ESOMsg) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ESOMsg_value, data, "ESOMsg")
	if err != nil {
		return err
	}
	*x = ESOMsg(value)
	return nil
}
func (ESOMsg) EnumDescriptor() ([]byte, []int) { return fileDescriptorGcsystemmsgs, []int{1} }

type EGCBaseClientMsg int32

const (
	EGCBaseClientMsg_k_EMsgGCClientWelcome          EGCBaseClientMsg = 4004
	EGCBaseClientMsg_k_EMsgGCServerWelcome          EGCBaseClientMsg = 4005
	EGCBaseClientMsg_k_EMsgGCClientHello            EGCBaseClientMsg = 4006
	EGCBaseClientMsg_k_EMsgGCServerHello            EGCBaseClientMsg = 4007
	EGCBaseClientMsg_k_EMsgGCClientConnectionStatus EGCBaseClientMsg = 4009
	EGCBaseClientMsg_k_EMsgGCServerConnectionStatus EGCBaseClientMsg = 4010
)

var EGCBaseClientMsg_name = map[int32]string{
	4004: "k_EMsgGCClientWelcome",
	4005: "k_EMsgGCServerWelcome",
	4006: "k_EMsgGCClientHello",
	4007: "k_EMsgGCServerHello",
	4009: "k_EMsgGCClientConnectionStatus",
	4010: "k_EMsgGCServerConnectionStatus",
}
var EGCBaseClientMsg_value = map[string]int32{
	"k_EMsgGCClientWelcome":          4004,
	"k_EMsgGCServerWelcome":          4005,
	"k_EMsgGCClientHello":            4006,
	"k_EMsgGCServerHello":            4007,
	"k_EMsgGCClientConnectionStatus": 4009,
	"k_EMsgGCServerConnectionStatus": 4010,
}

func (x EGCBaseClientMsg) Enum() *EGCBaseClientMsg {
	p := new(EGCBaseClientMsg)
	*p = x
	return p
}
func (x EGCBaseClientMsg) String() string {
	return proto.EnumName(EGCBaseClientMsg_name, int32(x))
}
func (x *EGCBaseClientMsg) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGCBaseClientMsg_value, data, "EGCBaseClientMsg")
	if err != nil {
		return err
	}
	*x = EGCBaseClientMsg(value)
	return nil
}
func (EGCBaseClientMsg) EnumDescriptor() ([]byte, []int) { return fileDescriptorGcsystemmsgs, []int{2} }

type EGCToGCMsg int32

const (
	EGCToGCMsg_k_EGCToGCMsgMasterAck             EGCToGCMsg = 150
	EGCToGCMsg_k_EGCToGCMsgMasterAckResponse     EGCToGCMsg = 151
	EGCToGCMsg_k_EGCToGCMsgRouted                EGCToGCMsg = 152
	EGCToGCMsg_k_EGCToGCMsgRoutedReply           EGCToGCMsg = 153
	EGCToGCMsg_k_EMsgUpdateSessionIP             EGCToGCMsg = 154
	EGCToGCMsg_k_EMsgRequestSessionIP            EGCToGCMsg = 155
	EGCToGCMsg_k_EMsgRequestSessionIPResponse    EGCToGCMsg = 156
	EGCToGCMsg_k_EGCToGCMsgMasterStartupComplete EGCToGCMsg = 157
)

var EGCToGCMsg_name = map[int32]string{
	150: "k_EGCToGCMsgMasterAck",
	151: "k_EGCToGCMsgMasterAckResponse",
	152: "k_EGCToGCMsgRouted",
	153: "k_EGCToGCMsgRoutedReply",
	154: "k_EMsgUpdateSessionIP",
	155: "k_EMsgRequestSessionIP",
	156: "k_EMsgRequestSessionIPResponse",
	157: "k_EGCToGCMsgMasterStartupComplete",
}
var EGCToGCMsg_value = map[string]int32{
	"k_EGCToGCMsgMasterAck":             150,
	"k_EGCToGCMsgMasterAckResponse":     151,
	"k_EGCToGCMsgRouted":                152,
	"k_EGCToGCMsgRoutedReply":           153,
	"k_EMsgUpdateSessionIP":             154,
	"k_EMsgRequestSessionIP":            155,
	"k_EMsgRequestSessionIPResponse":    156,
	"k_EGCToGCMsgMasterStartupComplete": 157,
}

func (x EGCToGCMsg) Enum() *EGCToGCMsg {
	p := new(EGCToGCMsg)
	*p = x
	return p
}
func (x EGCToGCMsg) String() string {
	return proto.EnumName(EGCToGCMsg_name, int32(x))
}
func (x *EGCToGCMsg) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGCToGCMsg_value, data, "EGCToGCMsg")
	if err != nil {
		return err
	}
	*x = EGCToGCMsg(value)
	return nil
}
func (EGCToGCMsg) EnumDescriptor() ([]byte, []int) { return fileDescriptorGcsystemmsgs, []int{3} }

type CMsgGCHVacVerificationChange struct {
	Steamid    uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid"`
	Appid      uint32 `protobuf:"varint,2,opt,name=appid" json:"appid"`
	IsVerified bool   `protobuf:"varint,3,opt,name=is_verified,json=isVerified" json:"is_verified"`
}

func (m *CMsgGCHVacVerificationChange) Reset()         { *m = CMsgGCHVacVerificationChange{} }
func (m *CMsgGCHVacVerificationChange) String() string { return proto.CompactTextString(m) }
func (*CMsgGCHVacVerificationChange) ProtoMessage()    {}
func (*CMsgGCHVacVerificationChange) Descriptor() ([]byte, []int) {
	return fileDescriptorGcsystemmsgs, []int{0}
}

func (m *CMsgGCHVacVerificationChange) GetSteamid() uint64 {
	if m != nil {
		return m.Steamid
	}
	return 0
}

func (m *CMsgGCHVacVerificationChange) GetAppid() uint32 {
	if m != nil {
		return m.Appid
	}
	return 0
}

func (m *CMsgGCHVacVerificationChange) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

type CMsgGCHAccountPhoneNumberChange struct {
	Steamid       uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid"`
	Appid         uint32 `protobuf:"varint,2,opt,name=appid" json:"appid"`
	PhoneId       uint64 `protobuf:"varint,3,opt,name=phone_id,json=phoneId" json:"phone_id"`
	IsVerified    bool   `protobuf:"varint,4,opt,name=is_verified,json=isVerified" json:"is_verified"`
	IsIdentifying bool   `protobuf:"varint,5,opt,name=is_identifying,json=isIdentifying" json:"is_identifying"`
}

func (m *CMsgGCHAccountPhoneNumberChange) Reset()         { *m = CMsgGCHAccountPhoneNumberChange{} }
func (m *CMsgGCHAccountPhoneNumberChange) String() string { return proto.CompactTextString(m) }
func (*CMsgGCHAccountPhoneNumberChange) ProtoMessage()    {}
func (*CMsgGCHAccountPhoneNumberChange) Descriptor() ([]byte, []int) {
	return fileDescriptorGcsystemmsgs, []int{1}
}

func (m *CMsgGCHAccountPhoneNumberChange) GetSteamid() uint64 {
	if m != nil {
		return m.Steamid
	}
	return 0
}

func (m *CMsgGCHAccountPhoneNumberChange) GetAppid() uint32 {
	if m != nil {
		return m.Appid
	}
	return 0
}

func (m *CMsgGCHAccountPhoneNumberChange) GetPhoneId() uint64 {
	if m != nil {
		return m.PhoneId
	}
	return 0
}

func (m *CMsgGCHAccountPhoneNumberChange) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

func (m *CMsgGCHAccountPhoneNumberChange) GetIsIdentifying() bool {
	if m != nil {
		return m.IsIdentifying
	}
	return false
}

func init() {
	proto.RegisterType((*CMsgGCHVacVerificationChange)(nil), "CMsgGCHVacVerificationChange")
	proto.RegisterType((*CMsgGCHAccountPhoneNumberChange)(nil), "CMsgGCHAccountPhoneNumberChange")
	proto.RegisterEnum("EGCSystemMsg", EGCSystemMsg_name, EGCSystemMsg_value)
	proto.RegisterEnum("ESOMsg", ESOMsg_name, ESOMsg_value)
	proto.RegisterEnum("EGCBaseClientMsg", EGCBaseClientMsg_name, EGCBaseClientMsg_value)
	proto.RegisterEnum("EGCToGCMsg", EGCToGCMsg_name, EGCToGCMsg_value)
}
func (m *CMsgGCHVacVerificationChange) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CMsgGCHVacVerificationChange) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x9
	i++
	i = encodeFixed64Gcsystemmsgs(dAtA, i, uint64(m.Steamid))
	dAtA[i] = 0x10
	i++
	i = encodeVarintGcsystemmsgs(dAtA, i, uint64(m.Appid))
	dAtA[i] = 0x18
	i++
	if m.IsVerified {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i++
	return i, nil
}

func (m *CMsgGCHAccountPhoneNumberChange) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CMsgGCHAccountPhoneNumberChange) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x9
	i++
	i = encodeFixed64Gcsystemmsgs(dAtA, i, uint64(m.Steamid))
	dAtA[i] = 0x10
	i++
	i = encodeVarintGcsystemmsgs(dAtA, i, uint64(m.Appid))
	dAtA[i] = 0x18
	i++
	i = encodeVarintGcsystemmsgs(dAtA, i, uint64(m.PhoneId))
	dAtA[i] = 0x20
	i++
	if m.IsVerified {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i++
	dAtA[i] = 0x28
	i++
	if m.IsIdentifying {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i++
	return i, nil
}

func encodeFixed64Gcsystemmsgs(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Gcsystemmsgs(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintGcsystemmsgs(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *CMsgGCHVacVerificationChange) Size() (n int) {
	var l int
	_ = l
	n += 9
	n += 1 + sovGcsystemmsgs(uint64(m.Appid))
	n += 2
	return n
}

func (m *CMsgGCHAccountPhoneNumberChange) Size() (n int) {
	var l int
	_ = l
	n += 9
	n += 1 + sovGcsystemmsgs(uint64(m.Appid))
	n += 1 + sovGcsystemmsgs(uint64(m.PhoneId))
	n += 2
	n += 2
	return n
}

func sovGcsystemmsgs(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozGcsystemmsgs(x uint64) (n int) {
	return sovGcsystemmsgs(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CMsgGCHVacVerificationChange) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGcsystemmsgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CMsgGCHVacVerificationChange: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CMsgGCHVacVerificationChange: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Steamid", wireType)
			}
			m.Steamid = 0
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 8
			m.Steamid = uint64(dAtA[iNdEx-8])
			m.Steamid |= uint64(dAtA[iNdEx-7]) << 8
			m.Steamid |= uint64(dAtA[iNdEx-6]) << 16
			m.Steamid |= uint64(dAtA[iNdEx-5]) << 24
			m.Steamid |= uint64(dAtA[iNdEx-4]) << 32
			m.Steamid |= uint64(dAtA[iNdEx-3]) << 40
			m.Steamid |= uint64(dAtA[iNdEx-2]) << 48
			m.Steamid |= uint64(dAtA[iNdEx-1]) << 56
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Appid", wireType)
			}
			m.Appid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGcsystemmsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Appid |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsVerified", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGcsystemmsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsVerified = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGcsystemmsgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGcsystemmsgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CMsgGCHAccountPhoneNumberChange) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGcsystemmsgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CMsgGCHAccountPhoneNumberChange: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CMsgGCHAccountPhoneNumberChange: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Steamid", wireType)
			}
			m.Steamid = 0
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 8
			m.Steamid = uint64(dAtA[iNdEx-8])
			m.Steamid |= uint64(dAtA[iNdEx-7]) << 8
			m.Steamid |= uint64(dAtA[iNdEx-6]) << 16
			m.Steamid |= uint64(dAtA[iNdEx-5]) << 24
			m.Steamid |= uint64(dAtA[iNdEx-4]) << 32
			m.Steamid |= uint64(dAtA[iNdEx-3]) << 40
			m.Steamid |= uint64(dAtA[iNdEx-2]) << 48
			m.Steamid |= uint64(dAtA[iNdEx-1]) << 56
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Appid", wireType)
			}
			m.Appid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGcsystemmsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Appid |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PhoneId", wireType)
			}
			m.PhoneId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGcsystemmsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PhoneId |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsVerified", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGcsystemmsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsVerified = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsIdentifying", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGcsystemmsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsIdentifying = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGcsystemmsgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGcsystemmsgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGcsystemmsgs(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGcsystemmsgs
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGcsystemmsgs
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGcsystemmsgs
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthGcsystemmsgs
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowGcsystemmsgs
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipGcsystemmsgs(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthGcsystemmsgs = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGcsystemmsgs   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("gcsystemmsgs.proto", fileDescriptorGcsystemmsgs) }

var fileDescriptorGcsystemmsgs = []byte{
	// 1440 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xc9, 0x73, 0x1b, 0xc5,
	0x1a, 0xf7, 0x44, 0x4e, 0x5e, 0xaa, 0xdf, 0xcb, 0x7b, 0x9d, 0x76, 0x1c, 0xaf, 0xb1, 0x1c, 0x67,
	0xf3, 0x73, 0xaa, 0x72, 0xc8, 0x5b, 0xd8, 0x17, 0x79, 0x2c, 0xcb, 0x0a, 0x76, 0x22, 0x24, 0xd9,
	0x66, 0x37, 0xed, 0x99, 0xcf, 0x52, 0x97, 0x35, 0xd3, 0x43, 0x77, 0xcb, 0xe0, 0x1b, 0x5c, 0xa0,
	0xb8, 0x71, 0x62, 0xe7, 0xc6, 0x52, 0xf0, 0x97, 0x98, 0xad, 0x8a, 0xe2, 0xc2, 0x05, 0x42, 0x70,
	0xfe, 0x00, 0x2e, 0xec, 0x27, 0x6a, 0xb6, 0x9e, 0x1e, 0x59, 0x86, 0x0b, 0x37, 0xe9, 0xfb, 0x7d,
	0x7b, 0xff, 0xbe, 0x6f, 0x3e, 0x44, 0x5a, 0x8e, 0xdc, 0x95, 0x0a, 0x3c, 0x4f, 0xb6, 0xe4, 0x95,
	0x40, 0x70, 0xc5, 0x67, 0x5e, 0xb0, 0xd0, 0xa4, 0xbd, 0x22, 0x5b, 0x15, 0x7b, 0x69, 0x8d, 0x3a,
	0x6b, 0x20, 0xd8, 0x16, 0x73, 0xa8, 0x62, 0xdc, 0xb7, 0xdb, 0xd4, 0x6f, 0x01, 0x99, 0x42, 0x7f,
	0x93, 0x0a, 0xa8, 0xc7, 0xdc, 0x51, 0x6b, 0xda, 0x9a, 0x3d, 0x36, 0x3f, 0xb8, 0x77, 0xb3, 0x38,
	0x50, 0x4f, 0x85, 0x64, 0x1c, 0x1d, 0xa5, 0x41, 0xc0, 0xdc, 0xd1, 0x23, 0xd3, 0xd6, 0xec, 0x89,
	0x04, 0x8d, 0x45, 0xe4, 0x02, 0xfa, 0x3b, 0x93, 0x1b, 0x3b, 0x91, 0x53, 0x70, 0x47, 0x0b, 0xd3,
	0xd6, 0xec, 0xf1, 0x44, 0x03, 0x31, 0xb9, 0x96, 0xc8, 0x67, 0xbe, 0xb4, 0x50, 0x31, 0xc9, 0xa1,
	0xe4, 0x38, 0xbc, 0xeb, 0xab, 0x5a, 0x9b, 0xfb, 0x70, 0xbd, 0xeb, 0x6d, 0x82, 0xf8, 0x0b, 0xd2,
	0x28, 0xa2, 0xe3, 0x41, 0xe8, 0x70, 0x83, 0xc5, 0x39, 0x0c, 0xa6, 0xc6, 0x91, 0xb4, 0x7a, 0x20,
	0xcf, 0xc1, 0xfe, 0x79, 0x92, 0xcb, 0xe8, 0x9f, 0x4c, 0x6e, 0x30, 0x17, 0x7c, 0xc5, 0xb6, 0x76,
	0x99, 0xdf, 0x1a, 0x3d, 0x6a, 0x68, 0x9e, 0x60, 0xb2, 0x9a, 0x41, 0x73, 0x5f, 0x0d, 0xa1, 0x7f,
	0x94, 0x2b, 0x76, 0x23, 0x6a, 0xf8, 0x8a, 0x6c, 0x91, 0x21, 0xf4, 0xaf, 0xed, 0x8d, 0x72, 0x25,
	0x2c, 0xb4, 0xea, 0xef, 0xd0, 0x0e, 0x73, 0xf1, 0x00, 0x39, 0x89, 0x4e, 0xa4, 0xc2, 0x95, 0x6e,
	0x47, 0x31, 0x6c, 0x91, 0x51, 0x74, 0x2a, 0x15, 0x55, 0xc0, 0x07, 0xc1, 0x9c, 0x3a, 0x04, 0x9d,
	0x5d, 0x8c, 0xc8, 0x69, 0x44, 0x52, 0x24, 0x76, 0x3b, 0x4f, 0x25, 0xe0, 0xab, 0x64, 0x0a, 0x8d,
	0xa7, 0xf2, 0x92, 0xd3, 0x66, 0xb0, 0x03, 0x1e, 0xf8, 0xaa, 0xf4, 0x2c, 0x15, 0x2e, 0xb8, 0xf8,
	0x3f, 0xa6, 0x9d, 0xcd, 0x7d, 0x9b, 0x7b, 0x1e, 0xf5, 0x5d, 0xfc, 0x5f, 0x33, 0x52, 0x43, 0x51,
	0xa1, 0x6a, 0x1d, 0x1a, 0xa6, 0x8e, 0xff, 0x47, 0x46, 0xd0, 0x50, 0x86, 0xf0, 0x20, 0x05, 0xfe,
	0x4f, 0x26, 0xd0, 0x48, 0xce, 0xa4, 0x42, 0x3d, 0x90, 0x20, 0x76, 0x40, 0xe0, 0x3b, 0xc8, 0x38,
	0x3a, 0x6d, 0x5a, 0x19, 0xd8, 0x9d, 0x64, 0x18, 0x9d, 0x4c, 0xb1, 0xf5, 0x4a, 0x1d, 0x9e, 0xe9,
	0x82, 0x54, 0xf8, 0x2e, 0x33, 0xb5, 0x50, 0x2c, 0x03, 0xee, 0x4b, 0xc0, 0x77, 0x93, 0x19, 0x34,
	0x95, 0x35, 0x41, 0xad, 0x4a, 0x10, 0xa1, 0xb7, 0x86, 0xa2, 0x4a, 0x36, 0x9c, 0x36, 0x78, 0x14,
	0xdf, 0x43, 0xe6, 0xd0, 0xc5, 0x3f, 0xd6, 0xd1, 0xfe, 0xee, 0xed, 0xe3, 0x2f, 0xd2, 0x5b, 0x28,
	0xd7, 0xea, 0x65, 0xbb, 0xd4, 0x2c, 0x2f, 0xe0, 0xfb, 0xc8, 0x34, 0x9a, 0xec, 0xa7, 0xa3, 0xbd,
	0xdc, 0x6f, 0x16, 0x58, 0x0a, 0x82, 0xaa, 0xbf, 0xc5, 0x57, 0x03, 0x97, 0x2a, 0x70, 0xf1, 0x03,
	0x66, 0x67, 0xd6, 0xc2, 0xc7, 0xa5, 0x0a, 0x1a, 0x20, 0x25, 0xe3, 0x3e, 0x7e, 0x90, 0x9c, 0x43,
	0xc5, 0x43, 0x40, 0xed, 0xbd, 0x64, 0xe6, 0xb8, 0xcc, 0xf9, 0x76, 0x37, 0x48, 0x86, 0x61, 0x51,
	0x70, 0xaf, 0xea, 0x07, 0x5d, 0x85, 0xe7, 0x73, 0xfd, 0x07, 0xdf, 0x5d, 0x6a, 0x36, 0x6b, 0x69,
	0x33, 0x6d, 0x33, 0x4a, 0x0f, 0xa8, 0xa3, 0x2c, 0x98, 0x8f, 0x5e, 0x13, 0xd0, 0x04, 0xa9, 0x1a,
	0xa0, 0xba, 0x01, 0x2e, 0x93, 0x22, 0x9a, 0x48, 0x91, 0x3a, 0x38, 0x5c, 0xb8, 0x8d, 0x6e, 0x10,
	0x70, 0xa1, 0x4a, 0x4e, 0xb8, 0x0e, 0xf0, 0x22, 0x99, 0x45, 0xe7, 0x8d, 0x06, 0x25, 0xd9, 0x2d,
	0x80, 0xa2, 0xac, 0x23, 0x37, 0x8c, 0x56, 0x56, 0xcc, 0x52, 0xea, 0xe0, 0x00, 0xdb, 0x81, 0xaa,
	0xaf, 0x40, 0x94, 0x82, 0x60, 0x05, 0xa4, 0xa4, 0x2d, 0xc0, 0x55, 0x33, 0x91, 0x45, 0xe6, 0xbb,
	0x89, 0x3b, 0x89, 0xaf, 0x99, 0x5c, 0xa9, 0x71, 0xa9, 0x4a, 0x1d, 0x10, 0x0a, 0x3f, 0x64, 0x92,
	0xb2, 0x02, 0x6a, 0x99, 0x39, 0xe0, 0x4b, 0x90, 0x78, 0x39, 0x3f, 0x31, 0xd9, 0xc3, 0xe1, 0x95,
	0x1e, 0x93, 0x84, 0xf9, 0x12, 0x5f, 0x37, 0x6b, 0x35, 0x00, 0xdd, 0xa6, 0x1b, 0xb9, 0xa7, 0x76,
	0xdd, 0x45, 0x01, 0x90, 0x04, 0xc4, 0x35, 0xb3, 0xba, 0x3c, 0xa6, 0xed, 0x1f, 0x26, 0x63, 0x68,
	0xd8, 0x08, 0x50, 0xad, 0x2d, 0xf3, 0x78, 0xab, 0xe2, 0x3a, 0x39, 0x8b, 0xce, 0xf4, 0x85, 0xb4,
	0x75, 0x83, 0x9c, 0x41, 0x63, 0xf9, 0x49, 0x37, 0x99, 0xdf, 0x34, 0x93, 0xab, 0x80, 0x32, 0x34,
	0xf0, 0x6a, 0x0f, 0xd3, 0x0d, 0x4c, 0xbb, 0x5f, 0x33, 0x1b, 0x1c, 0x12, 0xa5, 0xec, 0x51, 0xd6,
	0xc1, 0xeb, 0xb9, 0xa8, 0xa9, 0x58, 0x5b, 0x3d, 0x42, 0x26, 0xd1, 0xa8, 0xe1, 0x39, 0x42, 0x9b,
	0xe0, 0x05, 0x1d, 0xaa, 0x00, 0x3f, 0x4a, 0xce, 0xa3, 0xe9, 0xc3, 0x50, 0xed, 0xe3, 0xb1, 0x5c,
	0xe6, 0x82, 0xfa, 0xaa, 0x12, 0xb2, 0xb3, 0x46, 0xa5, 0xc4, 0x8f, 0xe7, 0x32, 0xcf, 0x61, 0xda,
	0xfe, 0x09, 0x33, 0xc5, 0x03, 0x14, 0xc4, 0x4f, 0x92, 0x0b, 0xe8, 0xec, 0xa1, 0xb0, 0xf6, 0xf2,
	0x94, 0x39, 0x45, 0x15, 0x50, 0x35, 0x10, 0x92, 0xfb, 0xf4, 0x7a, 0xb8, 0xae, 0xf0, 0x86, 0x39,
	0x45, 0x3d, 0xa0, 0xf6, 0xf0, 0xb4, 0x49, 0xb9, 0x68, 0x6f, 0x07, 0x1d, 0x78, 0x6e, 0x45, 0xb6,
	0x30, 0x35, 0xb7, 0x88, 0x89, 0x68, 0xdb, 0x4d, 0xb3, 0x53, 0xeb, 0xb0, 0x59, 0xaa, 0x55, 0xeb,
	0xd0, 0x62, 0x52, 0x81, 0x88, 0x66, 0x64, 0x8b, 0x3a, 0x20, 0x31, 0x98, 0xdd, 0x8e, 0xb5, 0xae,
	0xf1, 0xcd, 0x74, 0xd4, 0xb7, 0xcc, 0x51, 0xec, 0x45, 0x97, 0x94, 0x0a, 0x74, 0xb4, 0x36, 0xb9,
	0x8c, 0x2e, 0x1d, 0xa6, 0xb9, 0xc8, 0x45, 0xf8, 0x8d, 0xd0, 0xca, 0x8c, 0x8c, 0x19, 0x65, 0x81,
	0x67, 0x53, 0xa7, 0x0d, 0x6e, 0x05, 0x14, 0xde, 0xb3, 0xc8, 0x59, 0xa3, 0x2e, 0x03, 0xd2, 0xc6,
	0x1f, 0x5b, 0x7d, 0xad, 0x1b, 0xa0, 0xf0, 0x27, 0x16, 0x99, 0xcc, 0x3a, 0xae, 0xa1, 0x05, 0xe8,
	0x80, 0x02, 0xfc, 0xa9, 0x45, 0x26, 0x32, 0x56, 0x64, 0x86, 0x11, 0x9f, 0x3f, 0xb3, 0xc8, 0xb9,
	0x8c, 0x16, 0x79, 0x50, 0x87, 0xfe, 0xdc, 0x22, 0xc5, 0xec, 0x13, 0xb8, 0x42, 0xc3, 0x5e, 0x36,
	0x40, 0x2d, 0x30, 0x01, 0x8e, 0xe2, 0x62, 0x17, 0x7f, 0x6d, 0x91, 0x4b, 0x68, 0xe6, 0x70, 0x05,
	0xed, 0xe9, 0x9b, 0x7c, 0xb8, 0x54, 0x31, 0x79, 0x26, 0xde, 0x55, 0xe1, 0x57, 0xf0, 0xa6, 0x45,
	0x2e, 0x67, 0x9f, 0x9e, 0xfe, 0x4a, 0xda, 0xe3, 0xb7, 0x16, 0xb9, 0x98, 0x91, 0x52, 0x2b, 0xdb,
	0x1d, 0x06, 0xbe, 0x0a, 0x79, 0x91, 0x38, 0xbd, 0x65, 0x91, 0x2b, 0xe8, 0xdf, 0x7f, 0xaa, 0xa7,
	0xfd, 0x7e, 0x67, 0x91, 0x11, 0xe3, 0x1c, 0x00, 0x75, 0x23, 0x08, 0x77, 0x88, 0xc4, 0xfb, 0xb9,
	0x66, 0x64, 0x80, 0xb6, 0xbc, 0x1d, 0x9e, 0x18, 0x43, 0x07, 0x0f, 0x89, 0xab, 0xf8, 0x87, 0x82,
	0x59, 0x7d, 0x48, 0xfe, 0xae, 0x70, 0xda, 0x54, 0x42, 0x53, 0x74, 0xa5, 0x0a, 0x7b, 0xde, 0x95,
	0xf8, 0xc7, 0x82, 0x59, 0x7d, 0x7f, 0x25, 0x1d, 0xeb, 0xa7, 0x02, 0x19, 0xcf, 0x16, 0x61, 0xfc,
	0xb1, 0x4c, 0xbf, 0x8a, 0x3f, 0x17, 0xc8, 0x05, 0x63, 0x67, 0xd8, 0xc9, 0xb4, 0xae, 0x51, 0x27,
	0x76, 0x12, 0x1f, 0x7e, 0xf8, 0x97, 0x82, 0x49, 0x1e, 0xbb, 0x0d, 0xce, 0xf6, 0xa2, 0x60, 0xe0,
	0xbb, 0xb2, 0xcd, 0x02, 0xfc, 0x6b, 0x81, 0x9c, 0xcf, 0xe6, 0xb5, 0x07, 0xd5, 0x69, 0xfc, 0x56,
	0x20, 0x33, 0xd9, 0xd2, 0xed, 0x7b, 0xe7, 0xe2, 0x17, 0x07, 0xcd, 0x74, 0x0e, 0xbb, 0x43, 0xf1,
	0x4b, 0x83, 0x73, 0xdf, 0x5b, 0xe8, 0x58, 0xb9, 0x71, 0x23, 0xbb, 0xe9, 0xa2, 0xdf, 0x1b, 0xb6,
	0x80, 0x70, 0x13, 0x0e, 0xe7, 0x84, 0x71, 0xc9, 0xf8, 0x34, 0x39, 0x85, 0xb0, 0x16, 0x2e, 0x80,
	0x54, 0x82, 0xef, 0xe2, 0x91, 0x64, 0xc8, 0x13, 0xfb, 0x90, 0xd9, 0x8d, 0xee, 0xa6, 0x74, 0x04,
	0xdb, 0x04, 0x17, 0x8f, 0x26, 0x77, 0x9d, 0x81, 0xae, 0xfa, 0x32, 0xc3, 0xc7, 0x92, 0x35, 0x66,
	0x06, 0x4a, 0x37, 0x0e, 0x1e, 0x4f, 0xd6, 0xd8, 0x41, 0xd7, 0x41, 0x5c, 0x33, 0x38, 0xdb, 0x78,
	0x22, 0xd9, 0x97, 0x87, 0x28, 0xd5, 0x61, 0x4b, 0x80, 0x6c, 0xe3, 0xc9, 0xb9, 0x3d, 0x0b, 0xe1,
	0x72, 0xc5, 0x0e, 0x59, 0xa2, 0x09, 0x99, 0x3c, 0x6c, 0xf4, 0x74, 0xb1, 0x70, 0x1d, 0x3a, 0x0e,
	0xf7, 0x00, 0xbf, 0x5b, 0x34, 0xb1, 0x46, 0x74, 0x01, 0xa6, 0xd8, 0x7b, 0xc5, 0x84, 0x7c, 0x86,
	0xdd, 0x12, 0x74, 0x3a, 0x1c, 0xbf, 0x9f, 0x43, 0x62, 0xab, 0x18, 0xf9, 0xa0, 0x98, 0xd0, 0xd2,
	0xb0, 0xb1, 0xb9, 0xef, 0x43, 0x74, 0x97, 0x24, 0xb4, 0xfc, 0x30, 0xa7, 0x14, 0x9b, 0x1f, 0x50,
	0xfa, 0xa8, 0x38, 0xf7, 0xf2, 0x11, 0x84, 0xca, 0x15, 0xbb, 0xc9, 0xa3, 0x67, 0xd6, 0xec, 0x4c,
	0xfe, 0xc7, 0x73, 0x57, 0x72, 0xb6, 0xf1, 0xab, 0x96, 0xa6, 0x4c, 0x2f, 0xa6, 0x69, 0xf5, 0x5a,
	0x36, 0x83, 0x89, 0x4e, 0x38, 0xa5, 0xe0, 0xe2, 0xd7, 0xb3, 0x85, 0x97, 0x03, 0xe2, 0x43, 0xfe,
	0x0d, 0x2b, 0xeb, 0x4f, 0x6e, 0x24, 0xaa, 0x35, 0xfc, 0x66, 0xba, 0x0c, 0xa3, 0x4f, 0x46, 0xb4,
	0xa5, 0x33, 0xf0, 0x2d, 0x2b, 0xab, 0xb1, 0x17, 0xd4, 0x49, 0xbd, 0x9d, 0x2d, 0x9c, 0x5c, 0xe2,
	0xd1, 0xb9, 0xde, 0x0d, 0x6c, 0xee, 0x05, 0xd1, 0xda, 0x7d, 0xc7, 0x9a, 0x1f, 0xde, 0xdb, 0x9f,
	0xb2, 0xbe, 0xd8, 0x9f, 0xb2, 0x6e, 0xed, 0x4f, 0x59, 0xaf, 0xdc, 0x9e, 0x1a, 0x58, 0xb2, 0x9e,
	0xb7, 0x06, 0x7e, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xa7, 0xed, 0xad, 0xe3, 0x27, 0x0e, 0x00, 0x00,
}
